Add apiRoute helper method to simplify retrieving api routes
Saritasa/php-dingo-api-custom pull request #2
Opened 2017-11-03 11:26 UTC by VladimirBerdnik

2017-11-03 11:53 UTC, populov requested changes

2017-11-03 11:53 UTC, populov commented on CHANGES.md
> -Weeker typing requiredments for paging
Oops, my bad...

2017-11-03 11:53 UTC, populov commented on src/Request.php
> +class Request
I'd move this class to some package like saritasa/laravel-helpers, but I'm not sure, it worths to create one. Maybe move it to saritasa/laravel-middleware, and reference in this package?

2017-11-27 09:34 UTC, VladimirBerdnik commented
Changes added according to requested changes: https://github.com/Saritasa/php-laravel-middleware/pull/1

2018-01-09 17:20 UTC, VladimirBerdnik commented
up

2018-01-17 14:19 UTC, VladimirBerdnik commented
up

2018-01-19 10:58 UTC, populov approved these changes

2018-01-19 10:59 UTC, merged